name: validate-codecov-config

on:
  pull_request:
    paths: [codecov.yaml]
  push:
    paths-ignore:
      - "cookbooks/**"
    branches: [master]

jobs:
  validate-codecov-config:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Validate codecov configuration
        run: curl -sSL --fail-with-body --data-binary @codecov.yaml https://codecov.io/validate
